---

- name: Configure main
  template:
    src: "{{ apache2_main_config }}"
    dest: "{{ apache2_config_root }}/apache2.conf"
  notify: Reload apache2

- name: Remove default site
  file:
    state: absent
    mode: 0755
    path: "{{ apache2_vhosts_dir }}/000-default.conf"

- name: Create sites directory
  file:
    state: directory
    mode: 0755
    path: "{{ apache2_vhosts_dir }}"

- name: Create configs directory
  file:
    state: directory
    mode: 0755
    path: "{{ apache2_conf_dir }}"

- name: Enable base modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_base_modules|default(omit) }}"
  notify: Restart apache2

- name: Enable optional modules
  apache2_module:
    name: "{{ item }}"
    state: present
    ignore_configcheck: True
  with_items: "{{ apache2_optional_modules|default(omit) }}"
  when: apache2_optional_modules is defined
  notify: Restart apache2

- name: Configure vhosts
  template:
    src: "{{ item }}"
    dest: "{{ apache2_vhosts_dir }}"
  with_fileglob:
    - "{{ apache2_local_config_dir }}/sites-enabled/*.conf"
  notify: Reload apache2

- name: Aditional configs
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/conf-enabled"
  with_fileglob:
    - "{{ apache2_local_config_dir }}/conf-enabled/*.conf"
  notify: Reload apache2

- name: Allow HTTP
  ufw:
    port: "{{ apache2_http_port }}"
    proto: tcp
    rule: allow

- name: Allow HTTPS
  ufw:
    port: "{{ apache2_https_port }}"
    proto: tcp
    rule: allow
