---

- name: Configure main
  template:
    src: "{{ apache2_main_config }}"
    dest: "{{ apache2_config_root }}/apache2.conf"

- name: Create sites directory
  file:
    state: directory
    mode: 0755
    path: "{{ apache2_vhosts_dir }}"

- name: Create configs directory
  file:
    state: directory
    mode: 0755
    path: "{{ apache2_conf_dir }}"

- name: Configure vhosts
  template:
    src: "{{ item }}"
    dest: "{{ apache2_vhosts_dir }}"
  with_fileglob:
    - "{{ apache2_local_config_dir }}/sites-enabled/*.conf"

- name: Aditional configs
  template:
    src: "{{ item }}"
    dest: "{{ apache2_vhosts_dir }}"
  with_fileglob:
    - "{{ apache2_local_config_dir }}/conf-enabled/*.conf"

- name: Enable base modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_base_modules|default(omit) }}"

- name: Enable optional modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_optional_modules|default(omit) }}"
  when: apache2_optional_modules is defined

- name: Allow HTTP
  ufw:
    port: 80
    proto: tcp
    rule: allow

- name: Allow HTTPS
  ufw:
    port: 443
    proto: tcp
    rule: allow
