---
- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: Restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Reload apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes
